Don't publish tf if input frame == output frame
Otherwise, this will cause tf errors like this in subscribing nodes:

    Error:   TF_SELF_TRANSFORM: Ignoring transform from authority "/stereo_undistort" with frame_id and child_frame_id  "boson_right_optical_frame" because they are the same
             at line 221 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp